env:
  global:
  - secure: xQboVIZjyOqJqluJp3h0AJHX6yBqn0fcArk1vwD8KdBWUolydf63oG+ycc7QvZ6Y4isJCwNbmP0hsEBs/2/nDdrKKuTY7rZrbY4YKlRN3BHHLdfqOABIN8gsJOGbavPwedfGSReZnIsu7JadX6ks03jJ3WoxxWSVfq8DhPBEPCYGNDJF8EL54oeuDv6+r1yDrN3052CFbPr9mkAgEOwp1Pq41N+5gf/ibk1Fmq+1rndXYCT9QN0CdvL+i0t2q6iHVMwaHmuDphCz9ZEKo40RjJ23fIj8MMwznMuVUrSfNHRV+mhCRiiVKB0JQGAT1dXZ1BajPZq+N6k6fclQ8CwJkkF59i0VakEofYzISvjlel5+PplvGwPQ/kIUg8Tfg/Im/NHhUaDDe7N4bfdUbMDlsLTt17D4/LWsyESkX7Wfn4piCYEC364rQCsorgN14UN+SkIJaxjjw7cGT/ZBARi9i4ZGFZoJQ0OqdqJ2YSjNXsiPPbxC3Cf1BKLwRiwCFblo4yWB7r/tJ4gYAg2wYr9JtfvvF/B4F+ZxILELYKsD2TI2J8gSgG1tLnyZhH/r/E6Fvm6lRHBNkMLY5w2k3oHikGKqcXoruEfrh/cVKVQI012Hg4P+gi2bMimTF7k8JQcGK1dTy3qaJhAwHfEAiEReXyKVVh/ksSGnMWWl2MHxRiE=
  - secure: CCC2k5WDJFgeWTMBeh18x7I9Jj9IuU5S7pD3bF1Mw/ejheTw73m7EHJLwV7yqBENBJ4YtVkMNiZJHC6DUcSEpK3kTrBGFYKFb3c1uuNTSrigEdPiFKx2PrQOpKw9tVl47xVPHlJvmhPd0KorhjEw+xJu3zYbSpcEpl17Cmx1qdcFP4gfZtFoJlIi6fM3Ok/xW5xs3eCAbay8CX+lDSd3SMebIy130RnXK3PMcORv7HKAe6i90zLOLQRuCBLQOys9TAlreaPIQKxNQuZzGvGW7Nu6FsP2i3jPjupl8EFNMYvuBgerUIc2mzuDlb8hqL2dxHtgk8Wazl72d2y/FVkwSbuY1/CxLAjj8A3r7uGK0AYHv9LLw04BnfM5cVbiDy1PtQPNxh5hoD925nxXajC82YifxsWlyAE8JnBK99BhESR30J2bb7poXIP1T8eBKHuG7Q/08mnhwr6zR0GhJqy5XcJuya4kT6ANjzn6B7MHEgAHNqlaLRjGuwr+qbu0sbu53+Xdoaw9ewujOhNWu+U4QlR1lWuOU3GCu9LnH+rfDHOY5KvcFoYSX1sfjc30Z+6Rainh+5NtZlgBA8jnhLoPr8ZzDJSJniyqMt+a+ZSq91X2AsZxOMEFAxq1dwpzpatzek5Ckckl0gZSaTcCDxav/NsPNWuapFYmwBCtiWy+tNU=
  - REPO=p1hub/admin.protocol.one
sudo: true
services:
- docker
jobs:
  include:
  - stage: Building image with admin.protocol.one
    script:
    - export TAG=`if [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_TAG; fi`
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t $REPO:$TAG .
    - docker push $REPO
notifications:
  email: false
