version: '3'
services:
    p1-admin-php:
        build: .
        container_name: p1-admin-php
        networks: 
          - p1devnet
        restart: always

    p1-admin-nginx:
        container_name: p1-admin-nginx
        image: nginx:1.15.4
        networks: 
          - p1devnet
        ports:
            - "8011:80"
            - "8012:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - "p1-admin-php"

    p1-admin-mongo:
        image: mongo:4.1.3
        container_name: p1-admin-mongo
        networks: 
          - p1devnet
        restart: always
        volumes:
            - p1-admin-mongo:/data/db
        ports:
            - "8013:27017"

volumes:
  p1-admin-mongo:
    external: true

networks:
  p1devnet:
    external: true