parameters:
  default_locale: en
  default_secret: "GznmUbujd!nj&@VyjujBkv8#@Lj"

  secret: "t1dBMSLDbhdj3oEG3iSkL3dquY7C1GlD"
  mongodb_dsn: "mongodb://p1-admin-mongo:27017"
  mongodb_database: "p1admin"
  mongodb_user: ""
  mongodb_password: ""

  mongodb_server: "mongodb://p1-admin-mongo:27017"

  s3_bucket_name: '%env(S3_BUCKET_NAME)%'
  s3_region: '%env(S3_REGION)%'
  s3_access_key: '%env(S3_ACCESS_KEY)%'
  s3_secret_key: '%env(S3_SECRET_KEY)%'
  s3_version: '%env(S3_VERSION)%'
  s3_sdk_version: 3
