security:
  providers:
    in_memory:
      memory:
        users:
          demo:
            password: demo
            roles: 'ROLE_ADMIN'

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
    main:
      pattern:    ^/
      http_basic: true

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  access_control:
    - { path: ^/, roles: ROLE_ADMIN }