services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    admin.game:
        class: AppBundle\Admin\GameAdmin
        arguments: [~, AppBundle\Document\Game, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Game }
        public: true

    admin.game.genre:
        class: AppBundle\Admin\GenreAdmin
        arguments: [~, AppBundle\Document\Genre, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Genre }
        public: true

    admin.game.shortcut:
        class: AppBundle\Admin\ShortcutAdmin
        arguments: [~, AppBundle\Document\Shortcut, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Shortcut }
        public: true

    admin.gameSocialGroup:
        class: AppBundle\Admin\SocialGroupAdmin
        arguments: [~, AppBundle\Document\SocialGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: SocialGroup }
        public: true

    admin.gameSocialNetwork:
        class: AppBundle\Admin\SocialNetworkAdmin
        arguments: [~, AppBundle\Document\SocialNetwork, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: SocialNetwork }
        public: true

    admin.gameUI:
        class: AppBundle\Admin\GameUIAdmin
        arguments: [~, AppBundle\Document\GameUI, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: GameUI }
        public: true

    admin.gameHost:
        class: AppBundle\Admin\GameHostAdmin
        arguments: [~, AppBundle\Document\GameHost, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: GameHost }
        public: true

    admin.gameDownloadHook:
        class: AppBundle\Admin\DownloadHookAdmin
        arguments: [~, AppBundle\Document\DownloadHook, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: DownloadHook }
        public: true

    admin.gameDownloadHookType:
        class: AppBundle\Admin\DownloadHookTypeAdmin
        arguments: [~, AppBundle\Document\DownloadHookType, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: DownloadHookType }
        public: true

    admin.gameExecutorHook:
        class: AppBundle\Admin\ExecutorHookAdmin
        arguments: [~, AppBundle\Document\ExecutorHook, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: ExecutorHook }
        public: true

    admin.gameExecutorHookType:
        class: AppBundle\Admin\ExecutorHookTypeAdmin
        arguments: [~, AppBundle\Document\ExecutorHookType, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: ExecutorHookType }
        public: true

    admin.gridItem:
        class: AppBundle\Admin\GridItemAdmin
        arguments: [~, AppBundle\Document\GridItem, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: GridItem }
        public: true

    admin.grid:
        class: AppBundle\Admin\GridAdmin
        arguments: [~, AppBundle\Document\Grid, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Grid }
        public: true

    admin.theme:
        class: AppBundle\Admin\ThemeAdmin
        arguments: [~, AppBundle\Document\Theme, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Theme }
        public: true

    admin.gameMaintenance:
        class: AppBundle\Admin\MaintenanceAdmin
        arguments: [~, AppBundle\Document\Maintenance, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Maintenance }
        public: true

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Document\News, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: News }
        public: true

    admin.gameGallery:
        class: AppBundle\Admin\GalleryAdmin
        arguments: [~, AppBundle\Document\Gallery, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Gallery }
        public: true

    admin.gameBanner:
        class: AppBundle\Admin\BannerAdmin
        arguments: [~, AppBundle\Document\Banner, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Banner }
        public: true

    admin.gameAnnouncement:
        class: AppBundle\Admin\AnnouncementAdmin
        arguments: [~, AppBundle\Document\Announcement, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Announcement }
        public: true
