{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time}}    
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
      annotations:
        released: {{ .Release.Time}}
    spec:
      {{- if $deployment.configMap }}
      volumes:
      - name: {{ $deploymentName }}
        configMap:
          name: {{ $deploymentName }}
      {{- end }}
      containers:
      - name: {{ $deploymentName }}
        image: {{ $deployment.image }}:{{ $deployment.imageTag }}
        ports:
        - containerPort: {{ $deployment.port }}
        {{- if $deployment.configMap }}
        volumeMounts:
        - name: {{ $deploymentName }}
          mountPath: {{ $deployment.configMap.mountPath }}
          readOnly: true
        {{- end }}